### ISSUE TITLE
Date inputs are hard to use and can't be typed

### ISSUE THREAD

**Issue by water-e** [dwr-psandhu/dms_datastore_ui#13]
Recommend: 
1. start and end, not a "time window". There is no documentation on what that is or what syntax would be used with the next request ...
2. I like typing dates. I am faster than the gui tools.  I don't mind that they exist, but not having an option is a bummer. In that regard it would be nice if the format were self completing (ie if 2007-01-01 implied 2007-01-01T00:00). 
3. Despite what I just typed, the T would be optional or not used.

**Comment by dwr-psandhu** [comment]
What about datetime range? It is self explanatory and I don't have to validate "start" and "end". 

The widget library I am using provides these widgets. Take a look https://panel.holoviz.org/reference/index.html#widgets

I'll see what can be done but am open to options if supported by the library.

**Comment by dwr-psandhu** [comment]
Made an animated gif to show usage
![UseDateTimeRangePicker](https://github.com/dwr-psandhu/dms_datastore_ui/assets/11561317/dc1012f1-60c8-49ec-8f91-090053d82fdd)

**Comment by water-e** [comment]
I prefer start and end. I don't mind picking an AirB&B rental with that kind of widget since 80% of the time I'm working on a 10 day range and the view seems well constructed for that use case. But it offers no advantages for a 17 month query. By contrast my start and end for this query is always going to involve paging though months and years. That is very inconvenient. By contrast, NOAA (https://tidesandcurrents.noaa.gov/waterlevels.html?id=9414290) let's you mouse around in date pickers if you want but it will parse your date if you don't. They validate, not a big deal.

**Comment by water-e** [comment]
This gif  basically runs through a kind of best case that is fairly easy. The issue is that by the time you are readjusting one or the other a couple times it isn't clear whether you are adjusting the start or end anymore.  There is probably an answer, maybe it is even easy once you know the answer, but by then I have a negative feeling about the UI. I also disagree that date ranges (with that meaning, not pandas') is all that predominant.

**Comment by dwr-psandhu** [comment]
ok. I will just do a simple text box with date validation for start and end. As long as pandas.datetime is able to parse the string as a date it will be used.

If you take a look at the widget list, you can suggest another widget that matches your needs better.

**Comment by water-e** [comment]
My favorite is DatetimeRangeInput. It has the concept of range so it probably handles some of the range issues you wanted, though both its presentation and its retrieval are based on start and end which is how I code. It is simple text format with an example in the box and one that matches the timestamps we use. Similar to NOAA and CDEC in spirit. You might ditch the seconds. People will walk in and use this correctly the first time.

Two DatePickers would be OK if you strongly preferred a mousy interface. I don't  ... really prefer to type particularly when hours and minutes are involved. Also range validation would have to be coded. But what you said yesterday about typing in boxes still holds and now it isn't confusing whether I am typing the start or end.


________________________________
