### ISSUE TITLE
Add user flag editing using chart and or table interface

### ISSUE THREAD

**Issue by dwr-psandhu** [dwr-psandhu/dms_datastore_ui#19]
User flags are supported for screened level of data.

**Comment by dwr-psandhu** [comment]
user_flag "0" (which autoscreen does not assign) means user marked this as OK i.e. override the auto_screen and use value from formatted.
user_flag "1" means the user marks this as BAD
user_flag "" means UNCHECKED (which is the majority of the data after auto screen)
The user flagging system should not mark things "0" unless over-riding a previous "1".

**Comment by dwr-psandhu** [comment]
@water-e did I interpret user_flag correctly? Does the data in screened have the original data values for inspection or are they already cleansed of the value? In that case, do I have to read the formatted values to get value to display ?

**Comment by dwr-psandhu** [comment]
Fixed with commit https://github.com/dwr-psandhu/dms_datastore_ui/commit/122cbe284dbd4ab18ead954af28d810cbf1748b9

**Comment by water-e** [comment]
Or do I just launch from command line?
________________________________

**Comment by dwr-psandhu** [comment]
Launch from command line. You'll have to set the environment using the environment.yml at the top of this repo. Then you can pip install -e . 

Here's a sample command line for flag_editor and for data_screener as well
```
python dms_datastore_ui\flag_editor.py y:\repo\continuous\screened\ncro_bac_b95250_ec_*.csv
python dms_datastore_ui\data_screener.py y:\repo\continuous\screened\ncro_bac_b95250_ec_*.csv   
```
